name: Environments and Secrets on github actions
on:
    pull_request: 
        types: [opened,synchronize,reopened]
        branches:
            - main
env:
    PORT: 8080
jobs:
    test:
        environment: testing
        env:
            MONGODB_CLUSTER_ADDRESS: cluster0.k5mo0r5.mongodb.net
            MONGODB_DB_NAME: github-actions
            MONGODB_USERNAME: brownswizzy_db_user
            MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
        runs-on: ubuntu-latest
        steps:
            - name: clone code
              uses: actions/checkout@v5
            - name: cache dependencies 
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: app-deps-${{hashFiles('**/package-lock.json')}}
            - name: install deps
              run: npm ci --workspace=backend
           
            - name: run server
              run: npm start --workspace=backend & npx wait-on http://127.0.0.1:${{env.PORT}}
            - name: run tests
              run: npm run test --workspace=backend
            - name: deploying 
              run: echo "deploying ${{env.MONGODB_DB_NAME}} secret::${{env.MONGODB_PASSWORD}}"
