name: Event Filters and activities
# skipping ci
on:
    pull_request: 
        types: 
            - opened
            - synchronize
        branches:
            - main
            - 'dev-*'
            - 'feat/**'
    workflow_dispatch:

    push:
        branches: 
            - main
            - 'dev-*'
        paths-ignore:
            - '.github/workflows/*'
jobs: 
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: clone code
              uses: actions/checkout@v5
            - name: install deps
              run: npm ci --workspace=fronted
            - name: build code
              run: npm run build --workspace=frontends
            - name: deploy code
              run: echo "deploy.."