name: Job Artifacts
on: 
    push:
        branches: 
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
           - name: clone code 
             uses: actions/checkout@v5
           - name: install deps
             run: npm ci
           - name: lint code
             run: npm run lint 
           - name: run unit test
             run: npm run test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: clone code
              uses: actions/checkout@v5
            - name: install deps 
              run: npm ci
            - name: build code 
              run: npm run build
            - name: upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist-artifact
                path: |
                    dist
                    package.json
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: download build artifact
              uses: actions/download-artifact@v4
              with:
                name: dist-artifact
            - name: deploying
              run: echo "${{toJson(github.event)}}"
